### ISSUE TITLE
'Invalid status 6802'

### ISSUE THREAD

**Issue by webzrout** [LedgerHQ/ledger-live-desktop#2202]
- tested on Ledger Live ** Firmware version 1.5.5 / Ledger Live 1.11.0 **
- Platform and version: ** Windows 7 / Windows 10 / Windows 8.1 **

#### Actual Behavior:
In the Manager, the Bitcoin application is version number 1.3.11, but cannot be updated on the Ledger hardware where version 1.3.9 is still available.

Yesterday me and other users Ledger Nano S, or X reported the message 'Invalid status 6802'.
Today, apps will start to install and there is still no update when I want to install other apps, the manager writes: Install Bitcoin and Ethereum apps Requied. And so the whole thing keeps repeating itself with other apps...

Bye 
Screens:
https://imgur.com/a/nPP12v8
https://imgur.com/F3Ohy2I

**Comment by gre** [comment]
We are aware of the problem that I think was fixed yesterday. It was a backend/hsm issue.

**Comment by drPietro** [comment]
UP!
the problem is still there. It is impossibile to upgrade Bitcoin version from 1.3.9 to 1.3.11 and also, is not possibile to unistall it (becouse the manager writes: Install Bitcoin and Ethereum apps Requied) 

Testing with two Ledger Nano S

Ledger Nano S: ** Firmware version 1.5.5 **
Ledger Live: ** version 1.12.0 **
Platform: ** Windows 10 **
