### ISSUE TITLE
[Linux / Qubes] Ledger 2.0.1 doesn't work, graphics are not rendered properly.

### ISSUE THREAD

**Issue by d3adb33f** [LedgerHQ/ledger-live-desktop#2696]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.0.1**
- Platform and version: ~~**Debian 10**~~ Qubes

#### Expected behavior

Ledger Live should be able to start and render graphics properly.

#### Actual behavior

Once Legder Live is executed, the application takes around 30 seconds to load and graphics are displayed for a second and immediately after a black screen is presented invalidating any operation on Ledger Live 

I've also tried to delete all files under $HOME/.config/Ledger\ Live and it doesn't have any effect whatsoever.

#### Steps to reproduce the behavior

1- Download AppImage
2- Launch ledger live: ./ledger-live-desktop-2.0.1-linux-x86_64.AppImage

**Comment by d3adb33f** [comment]
I've made a small screencast (mp4) that shows the problem. Since github doesn't allows file upload, I've uploaded it [here](https://anonymousfiles.io/ESDdEMRF/)

**Comment by d3adb33f** [comment]
This screencast shows the problem:
![ledger](https://user-images.githubusercontent.com/7944405/76256351-16f0b180-6250-11ea-8061-19937e1ac4e5.gif)

**Comment by gre** [comment]
what is your graphics driver and window manager?
can you provide result of `uname -a`?

thanks

**Comment by d3adb33f** [comment]
> what is your graphics driver and window manager?

VGA compatible controller: Intel Corporation Device 5917 (rev 07)
Window manager: Xfce 4.12 - (xfwm4)

> can you provide result of `uname -a`?

Linux personal 4.19.94-1.pvops.qubes.x86_64 #1 SMP Sun Jan 12 05:45:26 UTC 2020 x86_64 GNU/Linux
> 
> thanks


I'm using Qubes, so it doesn't have a dedicate graphics card. In any event, Ledger Live 1.20 still works fine.

**Comment by gre** [comment]
In your video, what is weird is that you initially see the UI and then it fades away? a "smooth" fading way makes it really odd. I don't really understand what does that, maybe it's a bug with our splashscreen and/or some CSS transition that chrome don't correctly handle in context of your graphics driver.

in any case, i'm going to install Qubes (in VirtualBox for now) to see if I reproduce.

**Comment by d3adb33f** [comment]
Yes, the UI appears for a second and then fades away. Moving the window around or clicking inside it doesn't have any effect whatsoever.

I've made a few more tests and I was able to get the UI working as it should just by installing or removing libappindicator3-1, which is required for google chrome to work, directly into the AppVM.
However the UI fades away as illustrated in the video if the package is installed or removed from the template VM, which doesn't make any sense since the package base is the same.

libappindicator3-1 only install the lib and corresponding docs and contains the following files:

```
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libappindicator3-1
/usr/share/doc/libappindicator3-1/AUTHORS
/usr/share/doc/libappindicator3-1/README
/usr/share/doc/libappindicator3-1/changelog.Debian.gz
/usr/share/doc/libappindicator3-1/changelog.gz
/usr/share/doc/libappindicator3-1/copyright
/usr/lib/x86_64-linux-gnu/libappindicator3.so.1
```

So I guess the issue is related somehow with this library and Live Ledger, although it can only work if the library is installed/removed into the AppVM directly and not into the TemplateVM.

Can you advise??

**Comment by d3adb33f** [comment]
After some more troubleshooting I finally found the root cause!

I'm using wireguard on this AppVM and by default Wireguard sets its VIF in the sys-vpn with a MTU of 1420 while the other AppVms are using a MTU of 1500, which causes fragmentation and stall the initial connection request whenever Ledger is launched, resulting in the fading that's illustrated above.

Setting an MTU aligned to the sys-vpn solves the issue.

Ideally this would be much easier to spot if the UI send out an error or a message instead of silently fading failing and fading the graphics..

Can you include such option in the roadmap?


Thanks!

(I'm going to close this ticket, thanks for the assistance!)

**Comment by gre** [comment]
the way it errors by fading away is still mysterious to me yes. i'm glad this is fixed but I definitely would like to understand more why this happens (and this sounds easy to fix). I'll discuss with the team

**Comment by gre** [comment]
i'll remote the task so i don't forget about it. thanks for your feedback :)

**Comment by s3827035** [comment]
I am using a normal Windows and it is still happening. I am unable to use my wallet.

**Comment by gre** [comment]
This task is not for windows tho.

**Comment by makevoid** [comment]
if you get this on linux, it's possible that running ledger live with root / superuser priviledges will solve the issue, at least it did for me 

I had `CantOpenDevice","message":"cannot open device with path` in the ledger error logs and running `sudo ./ledger-live.sh --no-sandbox` solved the issue, I was able to complete the process and use my device again, hopefully this helps someone with the same issue :)

**Comment by CarloWood** [comment]
No sandbox doesn't sound like it is the right way to use it. What is the actual problem here?
