### ISSUE TITLE
Ubuntu 20.04 LTS not connecting to Ledger Wallet

### ISSUE THREAD

**Issue by MikeD10375** [LedgerHQ/ledger-live-desktop#2923]
#### Ledger Live Version and Operating System

- tested on Ledger Live **ledger-live-desktop-2.3.2-linux-x86_64.AppImage**
- Platform and version: **ASUS TUF GAMING FX505DU / Ubuntu 20.04 LTS**

#### Clean install of Ubuntu 20.04 (which is great) along with running before-mentioned appimage should reproduce problem. Hope I have given you enough detailed info to solve problem quickly and provide expedited software update. 

![Screenshot from 2020-05-15 19-38-28](https://user-images.githubusercontent.com/41456776/82105273-00604e00-970a-11ea-9a88-db0456da3dda.png)
![Screenshot from 2020-05-15 19-40-42](https://user-images.githubusercontent.com/41456776/82105274-05250200-970a-11ea-8c7d-531481dcbedb.png)

[savelog.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/4637570/savelog.txt)

**Comment by joe-bowman** [comment]
Same issue for me on a TUF GAMING 506-IU

The device shows in dmesg and lsusb, but is not seen by ledger live, other ledger libraries (e.g. the go sdk) or by the browser (u2f/fido - both brave and firefox)

**Comment by TheMattRay** [comment]
What a relief. Thought it was just me.

**Ran `dmesg` and get the following:**

[ 256.050799] usb 1-1.4: new full-speed USB device number 3 using xhci_hcd
[ 256.164193] usb 1-1.4: New USB device found, idVendor=2c97, idProduct=1011, bcdDevice= 2.01
[ 256.164208] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 256.164219] usb 1-1.4: Product: Nano S
[ 256.164229] usb 1-1.4: Manufacturer: Ledger
[ 256.164238] usb 1-1.4: SerialNumber: 0001
[ 256.244539] usbcore: registered new interface driver usbhid
[ 256.244546] usbhid: USB HID core driver
[ 256.279207] hid-generic 0003:2C97:1011.0001: hiddev0,hidraw0: USB HID v1.11 Device [Ledger Nano S] on usb-0000:01:00.0-1.4/input0


**My udev rules fileat /etc/udev/rules.d/20-hw1.rules looks like:**

# HW.1 / Nano
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1b7c|2b7c|3b7c|4b7c", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
# Blue
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0000|0000|0001|0002|0003|0004|0005|0006|0007|0008|0009|000a|000b|000c|000d|000e|000f|0010|00
11|0012|0013|0014|0015|0016|0017|0018|0019|001a|001b|001c|001d|001e|001f", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
# Nano S
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001|1000|1001|1002|1003|1004|1005|1006|1007|1008|1009|100a|100b|100c|100d|100e|100f|1010|10
11|1012|1013|1014|1015|1016|1017|1018|1019|101a|101b|101c|101d|101e|101f", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
# Aramis
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0002|2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|200a|200b|200c|200d|200e|200f|2010|20
11|2012|2013|2014|2015|2016|2017|2018|2019|201a|201b|201c|201d|201e|201f", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
# HW2
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0003|3000|3001|3002|3003|3004|3005|3006|3007|3008|3009|300a|300b|300c|300d|300e|300f|3010|30
11|3012|3013|3014|3015|3016|3017|3018|3019|301a|301b|301c|301d|301e|301f", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
# Nano X
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0004|4000|4001|4002|4003|4004|4005|4006|4007|4008|4009|400a|400b|400c|400d|400e|400f|4010|40
11|4012|4013|4014|4015|4016|4017|4018|4019|401a|401b|401c|401d|401e|401f", TAG+="uaccess", TAG+="udev-acl", owner="ubuntu"
#New Lines
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2c97"
KERNEL=="hidraw", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev", ATTRS{idVendor}=="2581"

**Comment by ninjavz** [comment]
Try: https://support.ledger.com/hc/en-us/articles/360006395553-Download-and-install-Ledger-Live
and: https://support.ledger.com/hc/en-us/articles/360026371854-Invalid-channel

**Comment by JamesKBowler** [comment]
any update on this?

Thanks

**Comment by MikeD10375** [comment]
Unfortunately not. Still waiting on a fix.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mgrodek** [comment]
hmm I have no problems with Ledger Live on Ubuntu 20.04. Just run sudo ./ledger-live-desktop-2.6.0-linux-x86_64.AppImage --no-sandbox and it connects properly..

**Comment by ninjavz** [comment]
Latest version 2.7.0 seems to work fine (Ubuntu 20.04)

**Comment by joe-bowman** [comment]
Setting the udev rules fixed this issue in my case.

**Comment by MikeD10375** [comment]
I'll have to install Ubuntu again to try it, but I'll let you know...Thanks for the info.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cthepot-ledger** [comment]
Assuming it is fixed as we have not heard from you @MikeD10375

**Comment by MikeD10375** [comment]
![Screenshot from 2020-09-23 13-47-39](https://user-images.githubusercontent.com/41456776/94050172-6f8b3480-fdc5-11ea-95ba-eaeb027350c6.png)

Still having the same problem as of release: ledger-live-desktop-2.11.1-linux-x86_64.AppImage

I've just been using the ledger live app. on my android phone since my programming skills aren't up to par and I have no idea how to fix this on the latest Ubuntu LTS...

**Comment by packetstracer** [comment]
+1 here

Ledger Nano S
ledger-live-desktop 2.2.3-nightly.20200414T2201
Ubuntu 20.04.1 LTS

**Comment by josehenriqueventura** [comment]
+1 here.

No news?

**Comment by josehenriqueventura** [comment]
I had the same issue and I ran the command below as a root user and worked. Ubuntu 20.04

sudo ./ledger-live-desktop-2.16.0-linux-x86_64.AppImage --no-sandbox

**Comment by nabeelmoeen** [comment]
thanks, the udev script fixed this for me

**Comment by gre** [comment]
Please make sure to use latest udev rules because I think a firmware release (last summer) have changed some product id:
See https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh

**Comment by josehenriqueventura** [comment]
> Please make sure to use latest udev rules because I think a firmware release (last summer) have changed some product id:
> See https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues
> 
> https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh

(1. Add the udev rules) Worked for me with ledger-live-desktop-2.16.0-linux-x86_64.AppImage version. Thanks!

**Comment by gre** [comment]
I'm glad to here this 👍

**Comment by foxreymann** [comment]
I've to sell my Ledgers. It is meant to help people, don't destroy they workflow. How a product consting mostly of bugs and data leaks be so promoted?

**Comment by theskyinflames** [comment]
> > Please make sure to use latest udev rules because I think a firmware release (last summer) have changed some product id:
> > See https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues
> > https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh
> 
> (1. Add the udev rules) Worked for me with ledger-live-desktop-2.16.0-linux-x86_64.AppImage version. Thanks!

This fix worked for me. I'm using Majaro Linux

Thanks!!!
