### ISSUE TITLE
Cant Vote for Tron on Ledger Live

### ISSUE THREAD

**Issue by richance** [LedgerHQ/ledger-live-desktop#3275]
#### Ledger Live Version and Operating System
Windows Ledger Live Desktop 2.15.0

#### Expected behavior

I want to vote in ledger live desktop with my tron trx.

#### Actual behavior

I can assign new votes but the continue button is grayed out 

also, i was voting for binance staking and now the validator is showing https://tronscan.org/#/address/3QJmnh which leads to nothing

please can you fix your ui?

**Comment by iamdarin** [comment]
i am getting the same issue.. the 2 pools i am staking with name changed to 3QJmnh as well and I am having a hard time voting. Only works if I cancel votes un freeze and refreeze and do entire amount i cannot keep previous votes and add to it as the button is greyed out.

**Comment by RedPlumpTomato** [comment]
Exactly what is happening to me. My vote shows:  3QJmnh as the validator and I can't find it on the voter list to reset back to 0. In fact, the list of votes shows completely empty for all validators.

**Comment by iamdarin** [comment]
I was able to connect ledger to tronscan and do all my voting there and it showed it was fine on ledger live.. definitely some update needed for ledger live

**Comment by gre** [comment]
We have breaking changes due to changes in our third party API. It will be fixed in our upcoming release (ETA 1 week)

**Comment by richance** [comment]
Working for me now in the newest version thank you!

**Comment by gre** [comment]
Thanks for confirmation.
Should be fixed indeed in 2.16

**Comment by gsardelli** [comment]
I'm using Ledger Live 2.3.2 but it still doesn't work for me.
 My vote shows: 3QJmnh.
 I can assign new votes but the continue button is grayed out.
 please can you fix your ui?
