### ISSUE TITLE
2.19 requires no-sandbox option in order to properly start in Mint 19

### ISSUE THREAD

**Issue by duartemvix** [LedgerHQ/ledger-live-desktop#3412]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.19.0**
- Platform and version: **Linux Mint 19 Debian**

#### Expected behavior

I was expecting to open the AppImage file normally after checking “execute it as a program” and just simply double clicking it. However, confronted with the app not loading at all I called it on the CLI and received the following message.

```
mat@mattops:/tmp$ /home/mat/ledger-live-desktop-2.19.0-linux-x86_64.AppImage
[3018:1223/133616.416349:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ledgerkch0gf/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (imagem do núcleo gravada)
mat@mattops:/tmp$ /home/mat/ledger-live-desktop-2.19.0-linux-x86_64.AppImage --no-sandbox
Ledger Live 2.19.0
init
Checking for update
spawned internal process 3106
Update for version 2.19.0 is not available (latest version: 2.19.0, downgrade is disallowed).
(node:3033) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
```

#### Actual behavior

```
mat@mattops:/tmp$ /home/mat/ledger-live-desktop-2.19.0-linux-x86_64.AppImage
[3018:1223/133616.416349:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ledgerkch0gf/chrome-sandbox is owned by root and has mode 4755.
```

#### Steps to reproduce the behavior

Download Ledger Live 2.19, right click the file, go into permissions and mark “execute it as program”. You should try to double click it and be confronted with an unresponsive program not loading at all.

**Comment by 1989gironimo** [comment]
Please test again with the newest updates, had this on Debian as well, but in testing it's resolved now.

**Comment by duartemvix** [comment]
> Please test again with the newest updates, had this on Debian as well, but in testing it's resolved now.

I still can't run it without appending --no-sandbox. But it still works fine.
